<div class='container pt-5'>
  <div class="row d-flex justify-content-center">
    <div class="col-sm-6" style="border-radius: 5%; background-color: white; border-radius: 20px; border: 2mm ridge rgba(187, 187, 187, .41);">
      <div class="py-3">
        <h3>カテゴリ編集</h3>
        <% object = session[:error_message] %>
        <% if !object.nil? %>
            <div class="alert alert-danger">
              <strong><%= object.count %>件のエラーが出たので変更を保存できませんでした。</strong>
            <ul>
            <% object.each do |msg| %>
              <%# message.each do |msg| %>
                <li><%= msg %></li>
              <%# end %>
            <% end %>
            </ul>
            </div>
        <% end %>
        <% session[:error_message] = nil %>
        <%= form_with model: @category, url: admin_category_path(@category), method: :patch, local:true do |f| %>
          <div class="form-group">
            <%= f.label :category_name, "カテゴリ名" %>
            <%= f.text_field :category_name, value: @category_name, class: 'form-control', style: "width:30%" %>
          </div>
          <div class="form-group">
            <%= f.submit "変更を保存", class: 'btn btn-outline-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>